### ISSUE TITLE
Issue running server

### ISSUE THREAD

**Issue by emaxsaun** [jas-bar/netjockey-server-node#1]
I just stumbled upon this today, when I run the server I get the following:

route-config.js:51
    throw 'Unable to load ' + routeItem.controller + ": " + e;
    ^
Unable to load ../controllers/v1/rooms/rooms-controller: Error: Cannot find module '../controllers/v1/rooms/rooms-controller'

**Comment by tomsik68** [comment]
Hi, thanks so much for giving this a try! 

The problem is, that `npm start` doesn't automatically compile coffeescript files. I'm looking into this. In the meanwhile, you can install coffeescript compiler (`coffee`) and then use it to compile the app/ folder. Just run `coffee --compile app` from the repo root. After that, I was able to start the server without problem.

**Comment by tomsik68** [comment]
I added `npm run-script build` to compile CoffeeScript files. It is described in README.

**Comment by emaxsaun** [comment]
Thanks so much! Giving it a shot now!

**Comment by emaxsaun** [comment]
Thanks so much. The server loads now. I ran into another small issue, when I load up a YouTube video I get this:

server/app/domain/youtube/youtube.js:31
            item = data['items'][0];
                       ^

TypeError: Cannot read property 'items' of undefined
    server/app/domain/youtube/youtube.js:31:24

Seems like data is undefined

**Comment by tomsik68** [comment]
I see, there seems to be a problem with the youtube library that we're using. I'll look into it later.
